// Generated by pivoshenko.theme. Do not edit by hand.
// Source: palettes/morok.json
// Consumer: pivoshenko.ui/packages/tailwind-preset

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        morok: {
          rosewater: '#e2cfc6',
          flamingo: '#d8b8aa',
          pink: '#d1b2c9',
          mauve: '#a78cc4',
          red: '#c98787',
          maroon: '#b97a74',
          peach: '#d0a178',
          yellow: '#c7b07a',
          green: '#8ea98c',
          teal: '#7ea59d',
          sky: '#7da2b5',
          sapphire: '#7398ad',
          blue: '#7f98bf',
          lavender: '#9faece',
          text: '#e7e5e4',
          subtext1: '#d6d3d1',
          subtext0: '#a8a29e',
          overlay2: '#a8a29e',
          overlay1: '#78716c',
          overlay0: '#57534e',
          surface2: '#292929',
          surface1: '#212121',
          surface0: '#191919',
          base: '#111111',
          mantle: '#0d0d0d',
          crust: '#000000',
        },
      },
      fontFamily: {
        sans: ['JetBrains Mono', 'monospace'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
}
